- name: Install zsh
  apt:
    name: zsh
    state: present

- name: Install oh-my-zsh for users with zsh shell
  shell: |
    RUNZSH=no CHSH=no KEEP_ZSHRC=yes \
    sh -c "$(curl -fsSL https://raw.githubusercontent.com/ohmyzsh/ohmyzsh/master/tools/install.sh)" "" --unattended
  args:
    chdir: "/home/{{ item.name }}"
    creates: "/home/{{ item.name }}/.oh-my-zsh"
  environment:
    HOME: "/home/{{ item.name }}"
    USER: "{{ item.name }}"
  loop: "{{ users_list | default([]) }}"
  when: item.shell == '/bin/zsh'
  become: true
